// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB86vWGRPmhIALgFaUL1Ck68ss7kdusj_I',
    appId: '1:438166588497:web:3c3a5375ef5f556867fc70',
    messagingSenderId: '438166588497',
    projectId: 'todo-applications-efbc9',
    authDomain: 'todo-applications-efbc9.firebaseapp.com',
    storageBucket: 'todo-applications-efbc9.appspot.com',
    measurementId: 'G-V6K395VFJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5yaxRduwNJGuU2EqvY_AKtpm2aHqcCSQ',
    appId: '1:438166588497:android:8f0a92b72189343167fc70',
    messagingSenderId: '438166588497',
    projectId: 'todo-applications-efbc9',
    storageBucket: 'todo-applications-efbc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAitRetjqVgFWDF5snSzi2J1xwc_BGpFtk',
    appId: '1:438166588497:ios:39adb8441e3f971b67fc70',
    messagingSenderId: '438166588497',
    projectId: 'todo-applications-efbc9',
    storageBucket: 'todo-applications-efbc9.appspot.com',
    iosBundleId: 'com.example.todoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAitRetjqVgFWDF5snSzi2J1xwc_BGpFtk',
    appId: '1:438166588497:ios:39adb8441e3f971b67fc70',
    messagingSenderId: '438166588497',
    projectId: 'todo-applications-efbc9',
    storageBucket: 'todo-applications-efbc9.appspot.com',
    iosBundleId: 'com.example.todoApplication',
  );
}
